version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "gradle"
    ignore:
      - dependency-name: "net.fabricmc.fabric-api:fabric-api"
        versions: ["4.x"]
    commit-message:
      prefix: "[DepUpdate]"
      include: "scope"