## Menu Visibility
menu.playerInfo.enabled=true
menu.serverInfo.enabled=true
menu.misc.enabled=true
menu.info.merged=false
menu.info.showGraphs=false

## Graph Settings
graph.fps=true
graph.clientMemory=true
graph.tps=true
graph.mspt=true
graph.serverMemory=true
graph.width=280
graph.height=80
graph.history=300

## Resource Pack
resourcepack.bypass=false
resourcepack.forceDeny=false
resourcepack.disableUnobf=false

## UI Packets
uipackets.delay=false
uipackets.send=true

## Sign / Bed
misc.shouldEditSign=true
misc.shouldForceWakeUp=false

## Misc Toggles
misc.shouldLogSounds=false
misc.shouldShowSlotNumbers=false
