name: Auto-merge Dependabot Updates

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
